version: '3.8'

services:
  streamlit_app:
    build: .
    image: streamlit:latest
    container_name: streamlit-app-service

    ports:
      - "8501:8501"
    networks:
      streamlit-network:
    # Command to run the Streamlit app
    command : ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]


networks:
  streamlit-network:
    driver: bridge