version: "3.8"
services:
  fast_api_server:
    build: .
    image: nlp-fast-api:latest
    container_name: nlp-api-service
    ports:
      - "8000:8000"
    networks:
      - api-network
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]


networks:
  api-network:
    driver: bridge